branches: [main]
plugins: [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    "@semantic-release/changelog",
    ["@semantic-release/git", {
      "assets": ['dist/**/*', 'CHANGELOG.md',
      'package.json', 'package-lock.json', 'npm-shrinkwrap.json']
    }],
    #"@semantic-release/github"
]
ci: false 