name: build
on:
  push:
    branches: [main]

jobs:
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm i @ui5/cli -g --ignore-scripts
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: git branch
      - run: git status
