name: release
on:
  push:
    branches: [master, main]

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
     pull-requests: write
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: node
          package-name: github-action-test-02
