name: release
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: github-action-test-02
      - run: |
          echo ${{ steps.release.outputs }}
          git branch
          git status
      - run: |
          npm run lint
          npm run test
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}