name: release
on:
  push:
    branches: [master, main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm run build
      - run: git branch
      - run: git status
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: github-action-test-02
      - run: |
          echo ${{ toJSON( steps ) }}
          git branch
          git status
      - run: |
          npm run lint
          npm run test
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}