name: release-build
on:
  push:
    branches: [release-please--branches--main]

# permissions: read-all

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
    - run: |
        npm ci --ignore-scripts
        npm run build
