name: test
on:
  push:
    branches: [master, main]
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: npm
    - run: |
        mkdir target
        npm i @ui5/cli -g --ignore-scripts
        npm ci --ignore-scripts
        npm run build
        npm run lint
        npm test
